<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'theseer\\cli\\coloredconsoleoutput' => '/output/ColoredConsoleOutput.php',
                'theseer\\cli\\command' => '/commands/Command.php',
                'theseer\\cli\\commandlocator' => '/commands/CommandLocator.php',
                'theseer\\cli\\commandlocatorexception' => '/commands/CommandLocatorException.php',
                'theseer\\cli\\commandoptions' => '/commands/CommandOptions.php',
                'theseer\\cli\\commandoptionsexception' => '/commands/CommandOptionsException.php',
                'theseer\\cli\\consoleinput' => '/input/ConsoleInput.php',
                'theseer\\cli\\consoleoutput' => '/output/ConsoleOutput.php',
                'theseer\\cli\\exceptionhandler' => '/ExceptionHandler.php',
                'theseer\\cli\\output' => '/output/Output.php',
                'theseer\\cli\\request' => '/Request.php',
                'theseer\\cli\\runner' => '/Runner.php',
                'theseer\\cli\\version' => '/Version.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
